config/routes.rb
Hubble::Application.routes.draw do
  root 'events#index'

  resources :events

  resources :sessions, only: [:create, :destroy]
  resources :users, only: [:new, :create]
  get "/login", to: 'sessions#new'
  get "/logout", to: 'sessions#destroy'
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :date, :start_time, :url
  validates :url, format: { with: /\A(http|https):\/\// }

  scope :chronologically, -> { order(:date, :start_time) }

  def pull_data_from_web!
    preview = LinkThumbnailer.generate(url)
    self.image_url = get_image_url(preview)
    self.title ||= preview.title
  end

  private

  def get_image_url(preview)
    # TODO: replace this logic when link_thumbnailer is updated to v2.0
    # https://github.com/gottfrois/link_thumbnailer/issues/32
    img = preview.images.first
    if img.is_a? FastImage
      img.source_url
    else
      img[:source_url]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :username
  validates_presence_of :password_digest, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :current_user

  def current_user
    @current_user = User.find_by(id: session[:user_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @event = Event.new(default_event)
    @events = Event.chronologically
  end

  def create
    @event = Event.new(event_params)
    @event.pull_data_from_web!

    if @event.save
      flash[:success] = "Event created!"
    else
      flash[:error] = "Error: Could not save Event. Please check your event"
    end

    redirect_to events_path
  end

  def destroy
    Event.find(params[:id]).destroy

    redirect_to events_path
  end

  private

  def default_event
    {
      date: Date.today,
      start_time: Time.now.midnight
    }
  end

  def event_params
    params.require(:event).permit(:title, :url, :description, :date, :start_time)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(username: username)
    if user && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid username or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def username
    params[:session][:username]
  end

  def password
    params[:session][:password]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Congratulations! Account was successfully created."
      redirect_to events_path
    else
      flash[:error] = "Error: Could not create user"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.slim
= simple_form_for event do |f|
  = f.input :date, as: :html5date
  = f.input :start_time, as: :html5time
  = f.input :url, label: "Link", input_html: { class: "input-xlarge" }
  = f.input :title
  = f.input :description
  = f.button :submit

app/views/events/index.html.slim
#event-form.modal.fade role="dialog" aria-hidden="true" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        = "Create a New Event"
        button.close data-dismiss="modal" aria-hidden="true"
          = "&times;".html_safe

      .modal-body
        = render "events/form", event: @event

.well
  button.btn.btn-lg data-toggle="modal" data-target="#event-form"
    = "Create Event"

- @events.each do |event|
    .well
      .pull-right.close.active
        = link_to "x", event_path(event), data:{ confirm: "Are you sure you want to remove this event?" }, method: :delete
      = link_to event.url do
        h4
          = event.title
        = image_tag event.image_url, class: "img-polaroid"
      p
      = event.description
      p
      = event.date.strftime "%a, %-b %-d, %Y"
      p
      = "Starting at #{event.start_time.strftime "%l:%M%P"}"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hubble" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Hubble</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <% if @current_user %>
                <li><%= link_to "Logout", logout_path  %></li>
              <% else %>
                <li><%= link_to "Login", login_path  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container body">
      <div class="row">
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
      <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/new.html.slim
= simple_form_for @user do |f|
  = f.input :username
  = f.input :password
  = f.input :password_confirmation
  = f.submit